export const DEFAULT_ACTION = 'APP/MENU/DEFAULT_ACTION';
export const STATE = 'APP/MENU/STATE';
export const SET_MENU_LIST_OK = 'APP/MENU/SET_MENU_LIST_OK';
export const MENU_LIST_REQUEST = 'APP/MENU/MENU_LIST_ACTIVES';
export const SET_CURRENT_SELECT = 'APP/MENU/SET_CURRENT_SELECT';
export const SET_DIALOG_STATE = 'APP/MENU/SET_DIALOG_STATE';
export const SET_BORDER_COLOR = 'APP/MENU/SET_BORDER_COLOR';
export const PREVIOUS_PAGER = 'APP/MENU/PREVIOUS_PAGER';
export const NEXT_PAGER = 'APP/MENU/NEXT_PAGER';
export const SET_PAGER = 'APP/SET_PAGER';
export const MENU_REQUESTS_GET_LIST = 'APP/MENU/MENU_REQUESTS_GET_LIST';

